### ISSUE TITLE
GET all books

### ISSUE THREAD

**Issue by MarcellNF** [neuefische/hh-java-24-1-team-example#1]
**As a User** 
**I need** to view a list of all my books
**to be able to** have a comprehensive overview of my entire library.

## Description
Implement a feature that allows users to retrieve and view a list of all their books from the backend.

## Acceptance Criteria

- [ ] Create a GET "/api/books" endpoint to fetch all books from the backend.
- [ ] Display the list of all books on the starting page of the frontend.

## Tasks

(for developers team)

- [ ] Create a Model with "Id, title and author"
- [ ] Create a "View All books" component in the UI.
- [ ] Implement a GET request to retrieve all books from the backend.
- [ ] Update the frontend to display the list of books.
- [ ] Implement Unit and Integration Test.
- [ ] add some styling
